- nbmctal.py: 		- break instructions changed in sys.exit() and corresponding warning messages redirected to stderr 		- added the capability of recognizing mesh tallies and cells from macrobodies. Now only working 		  with the latter. Mesh tallies stil raise an exit() for better control during test procedures. 	- loop_test: 		- implemented a cycle for separating the list of mctal files to be tested accordingly to the type 		  of error (mesh tally, macrobody tally, generic error, succesful test) 	- nbmctal2root.py: 		- minor changes: removed an unused cycle index 	- nbtestsuite.py: 		- break instructions changed in sys.exit() and corresponding warning messages redirected to stderr 		- macrobody facets are written correctly to the test file.
		Nicolò Borghi.

diff --git a/trunk/mcnp/nbmctal/loop_test b/trunk/mcnp/nbmctal/loop_test
--- a/trunk/mcnp/nbmctal/loop_test
+++ b/trunk/mcnp/nbmctal/loop_test
@@ -1,21 +1,63 @@
 #!/bin/bash
 
-echo "Testing..."
+VERBOSE=0
 
-SUM=0
+function help {
 
-for f in $@;
-do
-    python nbmctaltest.py $f -v
-    OUT=$?
-    SUM=$(($SUM+$OUT))
-done
+	echo "Usage: test [-v] file1 file2 ... "
+	exit 0   
 
-if [ $SUM -eq 0 ]; then
-    echo "OK"
-else
-    echo "FAILED"
+}
+
+function performTest () {
+
+	echo "Testing..."
+
+	SUM=0
+	ALL=0
+
+	if [[ "$VERBOSE" == "-v" ]]; then
+		shift 1
+	fi
+
+	for f in $@;
+	do
+		echo $f
+		python nbmctaltest.py $f $VERBOSE
+		OUT=$?
+		if [ $OUT -eq 5 ]; then
+			echo $f >> macrobody_fails
+			SUM=$(($SUM+1))
+		fi
+		if [ $OUT -eq 4 ]; then
+			echo $f >> mesh_fails
+			SUM=$(($SUM+1))
+		fi
+		if [ $OUT -eq 1 ]; then
+			echo $f >> generic_fails
+			SUM=$(($SUM+$OUT))
+		fi
+		if [ $OUT -eq 0 ]; then
+			echo $f >> successful_tests
+		fi
+		ALL=$(($ALL+1))
+	done
+
+	echo "$SUM out of $ALL Failed"
+	exit $SUM
+
+}
+
+if test $# -eq 0; then
+    help
 fi
 
-exit $SUM
+while getopts "hv" option; do
+    case $option in
+        h) help;;
+	v) VERBOSE="-v";;
+    esac
+done
+
+performTest $@
 
