loop_test needs list of mtal files as arguments. It returns number of non-passed tests.

diff --git a/trunk/mcnp/nbmctal/loop_test b/trunk/mcnp/nbmctal/loop_test
--- a/trunk/mcnp/nbmctal/loop_test
+++ b/trunk/mcnp/nbmctal/loop_test
@@ -4,16 +4,18 @@ echo "Testing..."
 
 SUM=0
 
-for f in mctal_files/*;
-	do
-		python nbmctaltest.py $f -v
-		OUT=$?
-		SUM=$(($SUM+$OUT))
-	done
+for f in $@;
+do
+    python nbmctaltest.py $f -v
+    OUT=$?
+    SUM=$(($SUM+$OUT))
+done
 
 if [ $SUM -eq 0 ]; then
-	echo "OK"
+    echo "OK"
 else
-	echo "FAILED"
+    echo "FAILED"
 fi
+
+exit $SUM
 
